# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Dimitar Dimitrov on Coding"

author:
  # facebook:         your-id
  # youtubeUser:      your-id
  # youtubeChannel:   your-id
  twitter:          dimitrov2k
  github:           n1ghtmare
  stackoverflow:    940072/dimitar-dimitrov
  # quora:            your-id
  # linkedin:         your-id
  # pinterest:        your-id
  # googlePlus:       your-id
  instagram:        dimitrov2k
  # reddit:           your-id
  # medium:           your-id
  # tumblr:           your-id
  email:            dimitrov2k@gmail.com

copyright:
  year:             2017
  name:             Dimitar Dimitrov

# Google-analytics
google-analytics:
  id:               "UA-104149938-1"

# Disqus
disqus:
  id:               "dimitrov-on-coding"

# URL
url:                "https://n1ghtmare.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Sofia
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  # - name:           "Github"
  #   url:            "https://github.com/AWEEKJ/Kiko-plus"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]